#!/usr/bin/env bash
# Transfers a file from a client to a server with scp

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    FILE_PATH="$1"
    SERVER_IP="$2"
    USERNAME="$3"
    SSH_KEY="$4"

    if [ "$#" -lt 4 ]; then
        scp -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
    else
        scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
    fi
fi
