#!/usr/bin/env bash
# Install and configure Nginx server

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx to listen on port 80
sudo ufw allow 'Nginx HTTP'

# Create index.html file with "Hello World!" content
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx without using systemctl
service nginx restart
