#!/usr/bin/env bash
# Update package lists
apt-get update

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80 and redirect /redirect_me
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
echo "
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location / {
        try_files \$uri \$uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart
