#!/usr/bin/env bash
# This script configures web-02 to be identical to web-01 and adds a custom Nginx response header

# Update system packages
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Configure firewall to allow incoming traffic on port 80
sudo ufw allow 'Nginx HTTP'

# Create directories for website content and error pages
sudo mkdir -p /var/www/html /var/www/error

# Set appropriate permissions for the website directories
sudo chmod -R 755 /var/www

# Create a basic index.html file with "Hello World!" content
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create a custom 404.html page with "Ceci n\'est pas une page" content
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Define the Nginx server configuration
server_config="
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    server_name _;
    add_header X-Served-By \$hostname;
    location / {
        try_files \$uri \$uri/ =404;
    }
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}"

# Write the server configuration to the default Nginx configuration file
echo "$server_config" | sudo tee /etc/nginx/sites-available/default

# Create a symbolic link to enable the server configuration
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx to apply the changes
sudo service nginx restart
