#!/usr/bin/env bash
# This script pings an IP address passed as an argument

if [ $# -eq 0 ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$1"

# This script checks if the number of arguments ($#) is equal to 0. If it is, it displays the usage message and exits with a non-zero status.
# Otherwise, it uses the `ping` command with the (-c) flag to ping the IP address passed as the first argument ($1) 5 times.
