#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.

# Requirements:

# Must show all processes, for all users, including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

# This script uses the ps command with the auxf options. The `a` option tells `ps` to show
# processes for all users, the 'u' option tells it to display the output in a user-oriented format,
# and the `x` option tells it to also show processes that don’t have a controlling terminal (TTY).
# The `f` option tells it to show the process hierarchy.

ps auxf
