#!/usr/bin/env bash
# help: read

# Write a Bash script that displays the content of the file `/etc/passwd`.

# Your script should only display:
# username, user id, and Home directory path for the user
# Requirements:
# You must use the while loop (for and until are forbidden)

while IFS=: read -r username _ userid _ _ homedir _; do
    echo "username: $username"
    echo "user id: $userid"
    echo "home directory: $homedir"
done < /etc/passwd
