#!/usr/bin/env bash
# This script tells a story based on the contents of the `/etc/passwd` file

myfile="/etc/passwd"
while IFS=: read -r username password userid groupid userinfo homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < $myfile
