#!/usr/bin/env bash
# This script displays Best School 10 times and Hi after the 9th using while and if

i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 10 ]
    then
        echo -e "Hi\nBest School"
    fi
    ((i++))
done
