#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu
ssh -i ~/.ssh/school -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" ubuntu@100.25.133.51
