#!/usr/bin/env bash
# Bash script that creates an RSA key pair
# Requirements:

# Name of the created private key must be `school`
# Number of bits in the created key to be created `4096`
# The created key must be protected by the passphrase `betty`

# Set the filename for the private key
private_key="school"

# Set the number of bits for the key
bits="4096"

# Set the passphrase for the key
passphrase="betty"

# Generate the key pair
ssh-keygen -b $bits -t rsa -f $private_key -N $passphrase

# Output success message
echo "Generating public/private rsa key pair."
echo "Your identification has been saved in $private_key."
echo "Your public key has been saved in $private_key.pub."
echo "The key fingerprint is:"
ssh-keygen -l -f $private_key
echo "The key's randomart image is:"

# Print the randomart image
ssh-keygen -lv -f $private_key
