#!/usr/bin/env bash
# Configure ssh client so that you can connect to a server without typing a password.
cat <<EOT >> ~/.ssh/config
Host *
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    GSSAPIDelegateCredentials no
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
EOT